# Generated by Django 5.1.4 on 2026-06-30 22:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Aeropuerto Internacional Benito Juárez', max_length=200, verbose_name='Nombre del aeropuerto')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('codigo_iata', models.CharField(help_text='Código de 3 letras. Ej: MEX, GDL, MTY', max_length=3, unique=True, verbose_name='Código IATA')),
                ('codigo_icao', models.CharField(blank=True, help_text='Código de 4 letras. Ej: MMMX, MMGL', max_length=4, null=True, unique=True, verbose_name='Código ICAO')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(help_text='Punto geográfico (longitud, latitud) del aeropuerto', srid=4326, verbose_name='Ubicación geográfica')),
                ('altitud_msnm', models.IntegerField(blank=True, help_text='Altitud en metros sobre el nivel del mar', null=True, verbose_name='Altitud (msnm)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Aeropuerto activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'db_table': 'aeropuertos',
                'ordering': ['codigo_iata'],
            },
        ),
    ]
