# Generated by Django 5.1.4 on 2026-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropuertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueloPNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vuelo', models.DateTimeField(db_index=True, help_text='Fecha y hora de salida del vuelo (UTC-6 CDMX)', verbose_name='Fecha y hora de salida')),
                ('nombre_aerolinea', models.CharField(help_text="Código IATA y nombre de la aerolínea. Ej: 'UA - UNITED AIRLINES'", max_length=120, verbose_name='Nombre de aerolínea')),
                ('numero_vuelo', models.CharField(help_text='Número de vuelo tal como lo registra la aerolínea', max_length=20, verbose_name='Número de vuelo')),
                ('ruta', models.CharField(db_index=True, help_text="Secuencia de aeropuertos separados por guión. Ej: 'MEX-CUN' o 'DFW-MEX-BOG'", max_length=120, verbose_name='Ruta completa')),
                ('aeropuerto_salida', models.CharField(db_index=True, help_text='Código IATA del aeropuerto de origen del viaje', max_length=10, verbose_name='Aeropuerto de salida (IATA)')),
                ('aeropuerto_llegada', models.CharField(db_index=True, help_text='Código IATA del aeropuerto de destino final del viaje', max_length=10, verbose_name='Aeropuerto de llegada (IATA)')),
                ('apis', models.IntegerField(default=0, help_text='Conteo de pasajeros según el sistema APIS (manifiesto previo al vuelo)', verbose_name='Pasajeros APIS')),
                ('pnr', models.IntegerField(default=0, help_text='Conteo de pasajeros según el sistema PNR (registro de reserva)', verbose_name='Pasajeros PNR')),
                ('dcs', models.IntegerField(default=0, help_text='Conteo de pasajeros según el sistema DCS (check-in y embarque real)', verbose_name='Pasajeros DCS')),
                ('fecha', models.DateField(db_index=True, help_text='Solo la fecha (sin hora), útil para agrupaciones diarias', verbose_name='Fecha de salida')),
                ('hora_salida', models.TimeField(help_text='Solo la hora de salida, útil para análisis de franjas horarias', verbose_name='Hora de salida')),
                ('mes', models.PositiveSmallIntegerField(db_index=True, help_text='Número de mes (1=Enero … 6=Junio)', verbose_name='Mes')),
                ('semana', models.PositiveSmallIntegerField(help_text='Número de semana ISO (1-53)', verbose_name='Semana del año')),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=Lunes, 1=Martes, … 6=Domingo', verbose_name='Día de la semana')),
                ('codigo_aerolinea', models.CharField(db_index=True, help_text="Primeras 2 (o 3) letras del código de aerolínea. Ej: 'UA', 'AM', 'Y4'", max_length=10, verbose_name='Código IATA de aerolínea')),
                ('nombre_corto_aerolinea', models.CharField(blank=True, help_text="Solo el nombre, sin el código. Ej: 'UNITED AIRLINES'. Vacío si no disponible.", max_length=100, verbose_name='Nombre corto de aerolínea')),
                ('num_segmentos', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de tramos en la ruta. 1=directo, 2=una escala, etc.', verbose_name='Número de segmentos')),
                ('pasajeros', models.IntegerField(db_index=True, default=0, help_text='Máximo entre APIS, PNR y DCS. DCS es el más preciso (pasajeros que abordaron), pero no siempre está disponible; el máximo es la estimación más conservadora.', verbose_name='Pasajeros (mejor estimación)')),
                ('cargado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga al sistema')),
            ],
            options={
                'verbose_name': 'Vuelo PNR',
                'verbose_name_plural': 'Vuelos PNR',
                'db_table': 'vuelos_pnr',
                'ordering': ['fecha_vuelo'],
                'indexes': [models.Index(fields=['aeropuerto_salida', 'aeropuerto_llegada'], name='idx_pnr_od_pair'), models.Index(fields=['codigo_aerolinea', 'fecha'], name='idx_pnr_aerolinea_fecha'), models.Index(fields=['mes', 'aeropuerto_salida'], name='idx_pnr_mes_salida')],
            },
        ),
    ]
